#!/bin/sh

progname="$(basename "$0")"

error () {
    # write $1 to stderr
    printf -- "$progname: %s\n" "$1" 1>&2
}

usage () {
    # show help
    cat <<EOF
usage: $progname [OPTIONS]
Show CPU usage.

Options:
       --help      show this help and exit

EOF
}

getopt -T 2> /dev/null
if [ $? -ne 4 ]; then
    error "unsupported version of getopt"
    exit 1
fi
long_opts=help
args="$(LC_ALL=C getopt -n "$progname" -s sh -o "" -l $long_opts -- "$@")"
if [ $? -eq 0 ]; then
    eval set -- "$args"
else
    exit 1
fi
while [ $# -gt 0 ]; do
    case "$1" in
	--help)
	    usage; exit 0;;
	--)
	    shift; break;;
	*)
	    break;;
    esac
    shift
done

if [ $# -gt 0 ]; then
    error "too many arguments"
    exit 1
fi

top -b -n 1 | head -n 20
