#!/bin/sh

progname="$(basename "$0")"

usage () {
    # show help
    cat <<EOF
usage: $progname [OPTIONS] [--] [FILE [FILE...]]
Rename files using Unix-friendly filenames.

Options:
 -d  --dots=N         number of dots allowed (default: 1)
 -o  --other=CHARS    other characters allowed in filenames
     --dry            dry run; do not rename
     --help           show this help and exit

By default the only characters allowed in filenames are alphanumeric
characters, nonconsecutive hyphens and the first dot counting from the
right.

A leading dot is always considered a valid character and does not
count as dot to the effects and purposes of option -d.

EOF
}

error () {
    # write $1 to stderr
    printf -- "$progname: %s\n" "$1" 1>&2
}

escape_bre () {
    # escape characters \, ], - and ^, which have a special meaning
    # inside awk bracket expressions
    printf "%s\n" "$1" | sed 's/[\]/\\\\\\&/g; s/[]^-]/\\\\&/g'
}

# awk program that does the actual job
unixfy_awk='
BEGIN {
    FS="[.]"
}
1 {
    sub(/\/$/, "")
    if (match($0, /.*[/]/)) {
	dirpart = substr($0, 1, RLENGTH)
	$0 = substr($0, RLENGTH+1)
    } else {
	dirpart = ""
    }
    if ($0 == "" || $0 ~ /^[.]{1,2}$/) {
        print ""
        next
    }
    if ($1 == "")
	leftdots = 1
    if (rightdots > -1) {
	while(NF > (rightdots+1))
	    sub(/[.]/, ",")
    }
    gsub(replacechars, "-")
    if (leftdots) {
	$0 = "." substr($0,2)
	leftdots = 0
    }
    do {
	if (match($0, /[^.]-([.]|$)/) || match($0, /[.]-[^.]/))
	    $0 = substr($0,1,RSTART) substr($0,RSTART+2)
    } while (RSTART)
    if (match($0, /^-[^.]/))
	$0 = substr($0,2)
    if ($0 ~ /^[.]{1,2}$/) {
        print ""
        next
    }
    printf "%s%s\n", dirpart, tolower($0)
}
'

# command line arguments
getopt -T 2> /dev/null
if [ $? -ne 4 ]; then
    error "unsupported version of getopt"
    exit 1
fi

short_opts=d:o:
long_opts=dots:,other:,dry,help

args="$(LC_ALL=C getopt -n "$progname" -s sh -o $short_opts -l $long_opts -- "$@")"
if [ $? -eq 0 ]; then
    eval set -- "$args"
else
    exit 1
fi

rightdots=1
otherchars=
dry=
while [ $# -gt 0 ]; do
    case "$1" in
	--help)
	    usage; exit 0 ;;
	-d|--dots)
	    rightdots="$2"; shift
	    if [ "$rightdots" -ne "$rightdots" ] 2> /dev/null; then
		error "option -d requires integer argument -- '$1'"
		exit 1
	    fi ;;
	-o|--other)
	    otherchars="$2"; shift ;;
	--dry)
	    dry=1 ;;
	--)
	    shift; break ;;
	*)
	    break
    esac
    shift
done

# check required args
if [ $# -lt 1 ]; then
    error "too few arguments"
    exit 1
fi

# printf "otherchars=$otherchars\n"
# printf "rightdots=$rightdots\n"
# printf "mv=$mv\n"
# printf "%s\n" "$@"
# exit

replacechars="[^[:alnum:].$(escape_bre "$otherchars")]+"

# test regular expression, as some combinations will produce errors
if ! printf "X\n" | awk "/$replacechars/" >/dev/null 2>&1; then
    error "invalid characters: $otherchars"
    exit 1
fi

# main loop
printf "%s\000" "$@" | \
    awk -v RS="\000" \
	-v replacechars="$replacechars" \
	-v rightdots=$rightdots \
	"$unixfy_awk" | \
    while read -r dest; do
	if [ "$1" != "$dest" ] && [ -n "$1" ] && [ -n "$dest" ]; then
	    if [ -n "$dry" ]; then
		printf "mv -i %s %s\n" "$1" "$dest"
	    else
		mv -i "$1" "$dest"
	    fi
	fi
	shift
    done
